CREATE TABLE IF NOT EXISTS media_item_versions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  media_item_id INT NOT NULL,
  product_id INT NOT NULL,
  lang VARCHAR(8) NOT NULL,
  source_raw_id INT DEFAULT NULL,
  version_no INT NOT NULL,
  filename VARCHAR(500) NOT NULL,
  display_name VARCHAR(255) DEFAULT NULL,
  object_key VARCHAR(500) NOT NULL,
  cover_object_key VARCHAR(500) DEFAULT NULL,
  file_url VARCHAR(1000) DEFAULT NULL,
  thumbnail_path VARCHAR(500) DEFAULT NULL,
  duration_seconds FLOAT DEFAULT NULL,
  file_size BIGINT DEFAULT NULL,
  task_id INT DEFAULT NULL,
  archived_by INT DEFAULT NULL,
  archived_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  archive_reason VARCHAR(64) DEFAULT NULL,
  deleted_at DATETIME DEFAULT NULL,
  deleted_by INT DEFAULT NULL,
  deleted_object_key VARCHAR(500) DEFAULT NULL,
  deleted_cover_object_key VARCHAR(500) DEFAULT NULL,
  KEY idx_item_versions (media_item_id, deleted_at, version_no),
  KEY idx_source_lang_versions (product_id, source_raw_id, lang, deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
