CREATE TABLE IF NOT EXISTS mingkong_material_sync_runs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  snapshot_date DATE NOT NULL,
  snapshot_at DATETIME NOT NULL,
  snapshot_slot VARCHAR(8) NOT NULL,
  ranking_snapshot_date DATE NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'running',
  source_product_limit INT NOT NULL DEFAULT 300,
  source_product_count INT NOT NULL DEFAULT 0,
  processed_product_count INT NOT NULL DEFAULT 0,
  material_count INT NOT NULL DEFAULT 0,
  failed_product_count INT NOT NULL DEFAULT 0,
  summary_json JSON NULL,
  error_message TEXT NULL,
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at DATETIME NULL,
  UNIQUE KEY uk_mk_material_run_snapshot_slot (snapshot_date, snapshot_slot),
  KEY idx_mk_material_run_snapshot_at (snapshot_at),
  KEY idx_mk_material_run_status_started (status, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mingkong_material_products (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  run_id BIGINT NOT NULL,
  snapshot_date DATE NOT NULL,
  snapshot_at DATETIME NOT NULL,
  snapshot_slot VARCHAR(8) NOT NULL,
  ranking_snapshot_date DATE NULL,
  rank_position INT NULL,
  product_code VARCHAR(255) NOT NULL,
  shopify_product_id VARCHAR(64) NULL,
  product_name VARCHAR(500) NULL,
  product_url VARCHAR(1000) NULL,
  store VARCHAR(128) NULL,
  sales_count INT NULL,
  order_count INT NULL,
  revenue_main VARCHAR(64) NULL,
  mk_product_id BIGINT NULL,
  mk_product_name VARCHAR(500) NULL,
  mk_product_link VARCHAR(1000) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  material_count INT NOT NULL DEFAULT 0,
  error_message TEXT NULL,
  processed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_mk_material_run_product (run_id, product_code),
  KEY idx_mk_material_product_snapshot_rank (snapshot_date, rank_position),
  KEY idx_mk_material_product_code (product_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mingkong_material_daily_snapshots (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  snapshot_date DATE NOT NULL,
  snapshot_at DATETIME NOT NULL,
  snapshot_slot VARCHAR(8) NOT NULL,
  ranking_snapshot_date DATE NULL,
  run_id BIGINT NULL,
  material_key CHAR(64) NOT NULL,
  product_code VARCHAR(255) NOT NULL,
  rank_position INT NULL,
  shopify_product_id VARCHAR(64) NULL,
  product_name VARCHAR(500) NULL,
  product_url VARCHAR(1000) NULL,
  mk_product_id BIGINT NULL,
  mk_product_name VARCHAR(500) NULL,
  mk_product_link VARCHAR(1000) NULL,
  main_image VARCHAR(1000) NULL,
  video_name VARCHAR(500) NULL,
  video_path VARCHAR(1000) NOT NULL,
  video_image_path VARCHAR(1000) NULL,
  cumulative_90_spend DECIMAL(14,2) NOT NULL DEFAULT 0,
  video_ads_count INT NOT NULL DEFAULT 0,
  video_author VARCHAR(128) NULL,
  video_upload_time VARCHAR(64) NULL,
  video_duration_seconds FLOAT NULL,
  mk_video_metadata_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_mk_material_snapshot_at_material (snapshot_at, material_key),
  KEY idx_mk_material_snapshot_spend (snapshot_at, cumulative_90_spend),
  KEY idx_mk_material_snapshot_product (product_code, snapshot_at),
  KEY idx_mk_material_snapshot_key_date (material_key, snapshot_at),
  KEY idx_mk_material_snapshot_date_slot (snapshot_date, snapshot_slot)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mingkong_material_daily_top100 (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  snapshot_date DATE NOT NULL,
  snapshot_at DATETIME NOT NULL,
  snapshot_slot VARCHAR(8) NOT NULL,
  previous_snapshot_date DATE NULL,
  previous_snapshot_at DATETIME NULL,
  previous_snapshot_slot VARCHAR(8) NULL,
  comparison_interval_seconds INT NULL,
  ranking_snapshot_date DATE NULL,
  rank_position INT NOT NULL,
  display_position INT NOT NULL,
  material_key CHAR(64) NOT NULL,
  product_code VARCHAR(255) NOT NULL,
  source_product_rank_position INT NULL,
  shopify_product_id VARCHAR(64) NULL,
  product_name VARCHAR(500) NULL,
  product_url VARCHAR(1000) NULL,
  mk_product_id BIGINT NULL,
  mk_product_name VARCHAR(500) NULL,
  mk_product_link VARCHAR(1000) NULL,
  main_image VARCHAR(1000) NULL,
  video_name VARCHAR(500) NULL,
  video_path VARCHAR(1000) NOT NULL,
  video_image_path VARCHAR(1000) NULL,
  previous_cumulative_90_spend DECIMAL(14,2) NULL,
  current_cumulative_90_spend DECIMAL(14,2) NOT NULL DEFAULT 0,
  yesterday_spend_delta DECIMAL(14,2) NOT NULL DEFAULT 0,
  video_ads_count INT NOT NULL DEFAULT 0,
  video_author VARCHAR(128) NULL,
  video_upload_time VARCHAR(64) NULL,
  video_duration_seconds FLOAT NULL,
  mk_video_metadata_json JSON NULL,
  is_new_material TINYINT(1) NOT NULL DEFAULT 0,
  is_new_top100_entry TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_mk_material_top100_snapshot_at_material (snapshot_at, material_key),
  KEY idx_mk_material_top100_display (snapshot_at, display_position),
  KEY idx_mk_material_top100_delta (snapshot_at, yesterday_spend_delta),
  KEY idx_mk_material_top100_key_date (material_key, snapshot_at),
  KEY idx_mk_material_top100_date_slot (snapshot_date, snapshot_slot)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
