CREATE TABLE IF NOT EXISTS dianxiaomi_rankings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id VARCHAR(32) NOT NULL COMMENT '店小秘/Shopify product ID',
  product_name VARCHAR(500) NOT NULL,
  product_url VARCHAR(1000) NULL,
  store VARCHAR(128) NULL,
  platform VARCHAR(64) NULL,
  parent_sku VARCHAR(128) NULL,
  order_count INT DEFAULT 0,
  sales_count INT DEFAULT 0,
  revenue_main VARCHAR(64) NULL COMMENT '付款销售额',
  revenue_split VARCHAR(64) NULL COMMENT '分摊销售额',
  refund_orders INT DEFAULT 0,
  refund_qty INT DEFAULT 0,
  refund_amt VARCHAR(64) NULL,
  refund_rate VARCHAR(16) NULL,
  media_product_id INT NULL COMMENT '关联 media_products.id',
  snapshot_date DATE NOT NULL COMMENT '数据抓取日期',
  rank_position INT NOT NULL COMMENT '排名',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_snapshot_product (snapshot_date, product_id),
  KEY idx_media_product (media_product_id),
  KEY idx_snapshot_rank (snapshot_date, rank_position)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
