-- 店小秘订单明细导入：批次表 + 订单商品行表

CREATE TABLE IF NOT EXISTS dianxiaomi_order_import_batches (
  id                         BIGINT AUTO_INCREMENT PRIMARY KEY,
  source                     VARCHAR(64)  NOT NULL DEFAULT 'dianxiaomi',
  date_from                  DATE         NOT NULL,
  date_to                    DATE         NOT NULL,
  status                     ENUM('running','success','failed','dry_run') NOT NULL DEFAULT 'running',
  started_at                 DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at                DATETIME     DEFAULT NULL,
  duration_seconds           INT UNSIGNED DEFAULT NULL,
  requested_site_codes       VARCHAR(255) NOT NULL,
  included_shopify_ids_count INT          NOT NULL DEFAULT 0,
  total_pages                INT          NOT NULL DEFAULT 0,
  fetched_orders             INT          NOT NULL DEFAULT 0,
  fetched_lines              INT          NOT NULL DEFAULT 0,
  inserted_lines             INT          NOT NULL DEFAULT 0,
  updated_lines              INT          NOT NULL DEFAULT 0,
  skipped_lines              INT          NOT NULL DEFAULT 0,
  error_message              MEDIUMTEXT   DEFAULT NULL,
  summary_json               JSON         DEFAULT NULL,
  created_at                 DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at                 DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_dxm_batches_started (started_at),
  KEY idx_dxm_batches_status (status),
  KEY idx_dxm_batches_dates (date_from, date_to)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Dianxiaomi order import batch runs';

CREATE TABLE IF NOT EXISTS dianxiaomi_order_lines (
  id                   BIGINT AUTO_INCREMENT PRIMARY KEY,
  batch_id             BIGINT       DEFAULT NULL,
  site_code            VARCHAR(64)  NOT NULL,
  product_id           INT          DEFAULT NULL COMMENT 'Matched local media_products.id',
  product_code         VARCHAR(128) DEFAULT NULL COMMENT 'Local media_products.product_code / Shopify handle',
  shopify_product_id   VARCHAR(64)  DEFAULT NULL,
  dxm_shop_id          VARCHAR(64)  DEFAULT NULL,
  dxm_shop_name        VARCHAR(255) DEFAULT NULL,
  dxm_package_id       VARCHAR(64)  NOT NULL,
  dxm_order_id         VARCHAR(128) DEFAULT NULL,
  extended_order_id    VARCHAR(128) DEFAULT NULL,
  package_number       VARCHAR(128) DEFAULT NULL,
  platform             VARCHAR(64)  DEFAULT NULL,
  order_state          VARCHAR(64)  DEFAULT NULL,
  buyer_name           VARCHAR(255) DEFAULT NULL,
  buyer_account        VARCHAR(255) DEFAULT NULL,
  product_name         VARCHAR(500) DEFAULT NULL,
  product_sku          VARCHAR(128) DEFAULT NULL,
  product_sub_sku      VARCHAR(128) DEFAULT NULL,
  product_display_sku  VARCHAR(128) DEFAULT NULL,
  variant_text         VARCHAR(500) DEFAULT NULL,
  quantity             INT          NOT NULL DEFAULT 1,
  unit_price           DECIMAL(12,2) DEFAULT NULL,
  line_amount          DECIMAL(12,2) DEFAULT NULL,
  order_amount         DECIMAL(12,2) DEFAULT NULL,
  order_currency       VARCHAR(16)   DEFAULT NULL,
  ship_amount          DECIMAL(12,2) DEFAULT NULL COMMENT 'Buyer-paid shipping amount from order.shipAmount',
  amount_with_shipping DECIMAL(12,2) DEFAULT NULL,
  amount_cny           DECIMAL(12,2) DEFAULT NULL,
  logistic_fee         DECIMAL(12,2) DEFAULT NULL COMMENT 'Actual logistics fee from orderProfit.logisticFee',
  profit               DECIMAL(12,2) DEFAULT NULL,
  refund_amount_usd    DECIMAL(12,2) DEFAULT NULL,
  refund_amount        DECIMAL(12,2) DEFAULT NULL,
  buyer_country        VARCHAR(16)  DEFAULT NULL,
  buyer_country_name   VARCHAR(128) DEFAULT NULL,
  province             VARCHAR(128) DEFAULT NULL,
  city                 VARCHAR(128) DEFAULT NULL,
  order_created_at     DATETIME     DEFAULT NULL,
  order_paid_at        DATETIME     DEFAULT NULL,
  paid_at              DATETIME     DEFAULT NULL,
  shipped_at           DATETIME     DEFAULT NULL,
  raw_order_json       JSON         NOT NULL,
  raw_line_json        JSON         NOT NULL,
  profit_json          JSON         DEFAULT NULL,
  imported_at          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_dxm_order_line (dxm_package_id, shopify_product_id, product_sku, product_sub_sku, product_display_sku),
  KEY idx_dxm_lines_batch (batch_id),
  KEY idx_dxm_lines_site_paid (site_code, order_paid_at),
  KEY idx_dxm_lines_shopify_product (shopify_product_id),
  KEY idx_dxm_lines_product_id (product_id),
  KEY idx_dxm_lines_country (buyer_country),
  CONSTRAINT fk_dxm_lines_batch FOREIGN KEY (batch_id) REFERENCES dianxiaomi_order_import_batches(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Dianxiaomi order line details imported from order APIs';
