-- Switch all video-translation copy/text translation bindings to OpenRouter Gemini 3 Flash.
-- Docs-anchor: docs/superpowers/specs/2026-05-13-video-translate-copy-openrouter-gemini3-flash.md

INSERT INTO llm_use_case_bindings (
  use_case_code,
  provider_code,
  model_id,
  extra_config,
  enabled,
  updated_by
) VALUES
  (
    'video_translate.localize',
    'openrouter',
    'google/gemini-3-flash-preview',
    NULL,
    1,
    NULL
  ),
  (
    'video_translate.tts_script',
    'openrouter',
    'google/gemini-3-flash-preview',
    NULL,
    1,
    NULL
  ),
  (
    'video_translate.rewrite',
    'openrouter',
    'google/gemini-3-flash-preview',
    NULL,
    1,
    NULL
  ),
  (
    'video_translate.source_normalize',
    'openrouter',
    'google/gemini-3-flash-preview',
    NULL,
    1,
    NULL
  ),
  (
    'video_translate.av_localize',
    'openrouter',
    'google/gemini-3-flash-preview',
    NULL,
    1,
    NULL
  ),
  (
    'video_translate.av_rewrite',
    'openrouter',
    'google/gemini-3-flash-preview',
    NULL,
    1,
    NULL
  ),
  (
    'asr_normalize.translate_zh_to_en',
    'openrouter',
    'google/gemini-3-flash-preview',
    NULL,
    1,
    NULL
  ),
  (
    'asr_normalize.translate_es_to_en',
    'openrouter',
    'google/gemini-3-flash-preview',
    NULL,
    1,
    NULL
  ),
  (
    'asr_normalize.translate_generic_to_en',
    'openrouter',
    'google/gemini-3-flash-preview',
    NULL,
    1,
    NULL
  ),
  (
    'ja_translate.localize',
    'openrouter',
    'google/gemini-3-flash-preview',
    NULL,
    1,
    NULL
  ),
  (
    'ja_translate.rewrite',
    'openrouter',
    'google/gemini-3-flash-preview',
    NULL,
    1,
    NULL
  ),
  (
    'translate_lab.shot_translate',
    'openrouter',
    'google/gemini-3-flash-preview',
    NULL,
    1,
    NULL
  ),
  (
    'translate_lab.tts_refine',
    'openrouter',
    'google/gemini-3-flash-preview',
    NULL,
    1,
    NULL
  )
ON DUPLICATE KEY UPDATE
  provider_code = VALUES(provider_code),
  model_id = VALUES(model_id),
  enabled = VALUES(enabled);
