-- Tabcut US daily selection snapshots.
-- Docs: docs/superpowers/specs/2026-05-12-tabcut-crawler-design.md

CREATE TABLE IF NOT EXISTS tabcut_crawl_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  biz_date DATE NOT NULL,
  region VARCHAR(8) NOT NULL DEFAULT 'US',
  status ENUM('running', 'success', 'failed') NOT NULL DEFAULT 'running',
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at DATETIME NULL,
  duration_seconds INT UNSIGNED NULL,
  request_count INT UNSIGNED NOT NULL DEFAULT 0,
  video_count INT UNSIGNED NOT NULL DEFAULT 0,
  goods_count INT UNSIGNED NOT NULL DEFAULT 0,
  candidate_count INT UNSIGNED NOT NULL DEFAULT 0,
  summary_json JSON NULL,
  error_message MEDIUMTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_tabcut_crawl_runs_date_region (biz_date, region),
  KEY idx_tabcut_crawl_runs_status_started (status, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tabcut_videos (
  video_id VARCHAR(64) NOT NULL PRIMARY KEY,
  region VARCHAR(8) NOT NULL DEFAULT 'US',
  author_name VARCHAR(255) NULL,
  author_avatar_url VARCHAR(1024) NULL,
  video_cover_url VARCHAR(1024) NULL,
  tk_video_url VARCHAR(1024) NULL,
  video_desc TEXT NULL,
  video_duration_ms INT UNSIGNED NULL,
  create_time DATETIME NULL,
  primary_item_id VARCHAR(64) NULL,
  primary_item_name TEXT NULL,
  raw_json JSON NULL,
  first_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_tabcut_videos_region_create (region, create_time),
  KEY idx_tabcut_videos_item (primary_item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tabcut_video_snapshots (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  biz_date DATE NOT NULL,
  region VARCHAR(8) NOT NULL DEFAULT 'US',
  video_id VARCHAR(64) NOT NULL,
  source_sort VARCHAR(32) NOT NULL,
  rank_position INT UNSIGNED NULL,
  play_count BIGINT UNSIGNED NULL,
  like_count BIGINT UNSIGNED NULL,
  share_count BIGINT UNSIGNED NULL,
  comment_count BIGINT UNSIGNED NULL,
  item_sold_count BIGINT UNSIGNED NULL,
  video_split_sold_count BIGINT UNSIGNED NULL,
  video_split_gmv DECIMAL(18, 4) NULL,
  related_item_id VARCHAR(64) NULL,
  related_item_name TEXT NULL,
  snapshot_json JSON NULL,
  crawled_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_tabcut_video_snapshot (biz_date, region, video_id, source_sort),
  KEY idx_tabcut_video_snapshots_rank (biz_date, region, source_sort, rank_position),
  KEY idx_tabcut_video_snapshots_item (biz_date, region, related_item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tabcut_goods (
  item_id VARCHAR(64) NOT NULL PRIMARY KEY,
  region VARCHAR(8) NOT NULL DEFAULT 'US',
  item_name TEXT NULL,
  item_pic_url VARCHAR(1024) NULL,
  category_id VARCHAR(64) NULL,
  category_name VARCHAR(255) NULL,
  category_l1_id VARCHAR(64) NULL,
  category_l1_name VARCHAR(255) NULL,
  category_l2_id VARCHAR(64) NULL,
  category_l2_name VARCHAR(255) NULL,
  category_l3_id VARCHAR(64) NULL,
  category_l3_name VARCHAR(255) NULL,
  seller_id VARCHAR(64) NULL,
  seller_name VARCHAR(255) NULL,
  seller_type VARCHAR(64) NULL,
  raw_json JSON NULL,
  first_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_tabcut_goods_region_category (region, category_l1_name(120), category_l2_name(120), category_l3_name(120)),
  KEY idx_tabcut_goods_seller (seller_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tabcut_goods_snapshots (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  biz_date DATE NOT NULL,
  region VARCHAR(8) NOT NULL DEFAULT 'US',
  item_id VARCHAR(64) NOT NULL,
  source VARCHAR(32) NOT NULL,
  rank_position INT UNSIGNED NULL,
  price_min DECIMAL(18, 4) NULL,
  price_max DECIMAL(18, 4) NULL,
  commission_rate DECIMAL(10, 6) NULL,
  sold_count_1d BIGINT UNSIGNED NULL,
  sold_count_7d BIGINT UNSIGNED NULL,
  sold_count_30d BIGINT UNSIGNED NULL,
  sold_count_total BIGINT UNSIGNED NULL,
  sold_count_period BIGINT UNSIGNED NULL,
  sold_growth_rate_1d DECIMAL(12, 6) NULL,
  sold_growth_rate_7d DECIMAL(12, 6) NULL,
  sold_growth_rate_30d DECIMAL(12, 6) NULL,
  sold_growth_rate_period DECIMAL(12, 6) NULL,
  gmv_1d DECIMAL(18, 4) NULL,
  gmv_7d DECIMAL(18, 4) NULL,
  gmv_30d DECIMAL(18, 4) NULL,
  gmv_total DECIMAL(18, 4) NULL,
  gmv_period DECIMAL(18, 4) NULL,
  related_video_count BIGINT UNSIGNED NULL,
  related_creator_count BIGINT UNSIGNED NULL,
  related_live_count BIGINT UNSIGNED NULL,
  discover_time DATETIME NULL,
  snapshot_json JSON NULL,
  crawled_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_tabcut_goods_snapshot (biz_date, region, item_id, source),
  KEY idx_tabcut_goods_snapshots_sales (biz_date, region, sold_count_7d, gmv_7d),
  KEY idx_tabcut_goods_snapshots_gmv (biz_date, region, gmv_period, gmv_total)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tabcut_video_candidates (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  biz_date DATE NOT NULL,
  region VARCHAR(8) NOT NULL DEFAULT 'US',
  video_id VARCHAR(64) NOT NULL,
  primary_item_id VARCHAR(64) NULL,
  score DECIMAL(18, 6) NOT NULL DEFAULT 0,
  score_parts_json JSON NULL,
  play_count BIGINT UNSIGNED NULL,
  item_sold_count BIGINT UNSIGNED NULL,
  video_split_sold_count BIGINT UNSIGNED NULL,
  video_split_gmv DECIMAL(18, 4) NULL,
  goods_sold_count_7d BIGINT UNSIGNED NULL,
  goods_gmv_7d DECIMAL(18, 4) NULL,
  goods_sold_count_total BIGINT UNSIGNED NULL,
  goods_gmv_total DECIMAL(18, 4) NULL,
  goods_growth_rate_7d DECIMAL(12, 6) NULL,
  category_l1_name VARCHAR(255) NULL,
  category_l2_name VARCHAR(255) NULL,
  category_l3_name VARCHAR(255) NULL,
  candidate_json JSON NULL,
  crawled_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_tabcut_video_candidate (biz_date, region, video_id),
  KEY idx_tabcut_video_candidates_score (biz_date, region, score),
  KEY idx_tabcut_video_candidates_category (biz_date, region, category_l1_name, category_l2_name, category_l3_name),
  KEY idx_tabcut_video_candidates_sales (biz_date, region, item_sold_count, goods_sold_count_7d, goods_gmv_7d)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
