CREATE TABLE IF NOT EXISTS xuanpin_today_recommendation_runs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  recommendation_date DATE NOT NULL,
  ranking_snapshot_date DATE NULL,
  source_limit INT NOT NULL DEFAULT 500,
  target_products INT NOT NULL DEFAULT 20,
  target_materials INT NOT NULL DEFAULT 100,
  status VARCHAR(24) NOT NULL DEFAULT 'running',
  ai_provider VARCHAR(64) NULL,
  ai_model VARCHAR(128) NULL,
  summary_json JSON NULL,
  output_file VARCHAR(512) NULL,
  error_message TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at DATETIME NULL,
  KEY idx_reco_date_created (recommendation_date, created_at),
  KEY idx_status_created (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS xuanpin_today_recommendations (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  run_id BIGINT NULL,
  recommendation_date DATE NOT NULL,
  ranking_snapshot_date DATE NOT NULL,
  candidate_key CHAR(64) NOT NULL,
  product_recommendation_rank INT NOT NULL,
  material_rank INT NOT NULL,
  overall_score DECIMAL(6,2) NOT NULL DEFAULT 0,
  product_key VARCHAR(255) NOT NULL,
  product_handle VARCHAR(255) NULL,
  shopify_product_id VARCHAR(64) NULL,
  product_name VARCHAR(500) NOT NULL,
  product_url VARCHAR(1000) NULL,
  sales_count INT NULL,
  order_count INT NULL,
  revenue_main VARCHAR(64) NULL,
  rank_position INT NULL,
  mk_product_id INT NULL,
  mk_product_name VARCHAR(500) NULL,
  mk_total_spends DECIMAL(12,2) NULL DEFAULT 0,
  mk_total_ads INT NULL DEFAULT 0,
  mk_video_count INT NULL DEFAULT 0,
  video_name VARCHAR(500) NULL,
  video_path VARCHAR(1000) NULL,
  video_image_path VARCHAR(1000) NULL,
  video_spends DECIMAL(12,2) NULL DEFAULT 0,
  video_ads_count INT NULL DEFAULT 0,
  video_author VARCHAR(128) NULL,
  video_upload_time VARCHAR(64) NULL,
  video_duration_seconds FLOAT NULL,
  recommended_countries JSON NULL,
  ai_reason TEXT NULL,
  ai_detail_json JSON NULL,
  mk_video_metadata_json JSON NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'pending',
  media_product_id INT NULL,
  media_item_id INT NULL,
  adopted_task_id INT NULL,
  adopted_by INT NULL,
  adopted_at DATETIME NULL,
  error_message TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_reco_date_candidate (recommendation_date, candidate_key),
  KEY idx_reco_status_rank (recommendation_date, status, product_recommendation_rank, material_rank),
  KEY idx_candidate_status (candidate_key, status),
  KEY idx_run (run_id),
  KEY idx_adopted_task (adopted_task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
