CREATE TABLE IF NOT EXISTS roi_hourly_sync_runs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  task_code VARCHAR(64) NOT NULL DEFAULT 'roi_hourly_sync',
  status ENUM('running','success','failed','partial') NOT NULL DEFAULT 'running',
  sync_started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  sync_finished_at DATETIME DEFAULT NULL,
  duration_seconds INT UNSIGNED DEFAULT NULL,
  window_start_at DATETIME NOT NULL,
  window_end_at DATETIME NOT NULL,
  lookback_hours INT NOT NULL DEFAULT 3,
  dxm_import_batch_id BIGINT DEFAULT NULL,
  order_hours_upserted INT NOT NULL DEFAULT 0,
  meta_hours_upserted INT NOT NULL DEFAULT 0,
  overview_hours_upserted INT NOT NULL DEFAULT 0,
  error_message MEDIUMTEXT DEFAULT NULL,
  summary_json JSON DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_roi_runs_started (sync_started_at),
  KEY idx_roi_runs_status_started (status, sync_started_at),
  KEY idx_roi_runs_window (window_start_at, window_end_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Real ROAS hourly sync task runs';

CREATE TABLE IF NOT EXISTS roi_hourly_order_facts (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  hour_start_at DATETIME NOT NULL,
  hour_end_at DATETIME NOT NULL,
  timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai',
  order_source VARCHAR(64) NOT NULL DEFAULT 'dianxiaomi',
  store_scope VARCHAR(128) NOT NULL DEFAULT 'newjoy,omurio',
  order_count INT NOT NULL DEFAULT 0,
  line_count INT NOT NULL DEFAULT 0,
  units INT NOT NULL DEFAULT 0,
  order_revenue_usd DECIMAL(14,2) NOT NULL DEFAULT 0,
  line_revenue_usd DECIMAL(14,2) NOT NULL DEFAULT 0,
  shipping_revenue_usd DECIMAL(14,2) NOT NULL DEFAULT 0,
  first_order_at DATETIME DEFAULT NULL,
  last_order_at DATETIME DEFAULT NULL,
  last_run_id BIGINT DEFAULT NULL,
  source_updated_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_roi_order_hour_scope (hour_start_at, order_source, store_scope),
  KEY idx_roi_order_hour (hour_start_at),
  KEY idx_roi_order_last_order (last_order_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Hourly order facts for real ROAS';

CREATE TABLE IF NOT EXISTS roi_hourly_meta_facts (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  hour_start_at DATETIME NOT NULL,
  hour_end_at DATETIME NOT NULL,
  timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai',
  ad_platform VARCHAR(32) NOT NULL DEFAULT 'meta',
  ad_account_id VARCHAR(64) DEFAULT NULL,
  account_scope VARCHAR(128) NOT NULL DEFAULT 'all',
  spend_usd DECIMAL(14,4) NOT NULL DEFAULT 0,
  impressions INT NOT NULL DEFAULT 0,
  clicks INT NOT NULL DEFAULT 0,
  purchase_value_usd DECIMAL(14,4) NOT NULL DEFAULT 0,
  purchases INT NOT NULL DEFAULT 0,
  source_status VARCHAR(32) NOT NULL DEFAULT 'pending_source',
  raw_json JSON DEFAULT NULL,
  last_run_id BIGINT DEFAULT NULL,
  source_updated_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_roi_meta_hour_scope (hour_start_at, ad_platform, account_scope),
  KEY idx_roi_meta_hour (hour_start_at),
  KEY idx_roi_meta_status (source_status, hour_start_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Hourly Meta ad spend facts for real ROAS';

CREATE TABLE IF NOT EXISTS roi_hourly_overview_facts (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  hour_start_at DATETIME NOT NULL,
  hour_end_at DATETIME NOT NULL,
  timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai',
  store_scope VARCHAR(128) NOT NULL DEFAULT 'newjoy,omurio',
  ad_platform_scope VARCHAR(128) NOT NULL DEFAULT 'meta',
  order_count INT NOT NULL DEFAULT 0,
  units INT NOT NULL DEFAULT 0,
  order_revenue_usd DECIMAL(14,2) NOT NULL DEFAULT 0,
  shipping_revenue_usd DECIMAL(14,2) NOT NULL DEFAULT 0,
  ad_spend_usd DECIMAL(14,4) NOT NULL DEFAULT 0,
  true_roas DECIMAL(12,6) DEFAULT NULL,
  order_data_status VARCHAR(32) NOT NULL DEFAULT 'ok',
  ad_data_status VARCHAR(32) NOT NULL DEFAULT 'pending_source',
  last_run_id BIGINT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_roi_overview_hour_scope (hour_start_at, store_scope, ad_platform_scope),
  KEY idx_roi_overview_hour (hour_start_at),
  KEY idx_roi_overview_status (ad_data_status, hour_start_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Hourly real ROAS overview facts';

CREATE TABLE IF NOT EXISTS roi_realtime_daily_snapshots (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  snapshot_at DATETIME NOT NULL,
  business_date DATE NOT NULL,
  timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai',
  store_scope VARCHAR(128) NOT NULL DEFAULT 'newjoy,omurio',
  ad_platform_scope VARCHAR(128) NOT NULL DEFAULT 'meta',
  order_count INT NOT NULL DEFAULT 0,
  line_count INT NOT NULL DEFAULT 0,
  units INT NOT NULL DEFAULT 0,
  order_revenue_usd DECIMAL(14,2) NOT NULL DEFAULT 0,
  shipping_revenue_usd DECIMAL(14,2) NOT NULL DEFAULT 0,
  ad_spend_usd DECIMAL(14,4) NOT NULL DEFAULT 0,
  order_data_status VARCHAR(32) NOT NULL DEFAULT 'ok',
  ad_data_status VARCHAR(32) NOT NULL DEFAULT 'pending_source',
  last_order_at DATETIME DEFAULT NULL,
  source_run_id BIGINT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_roi_snapshot_node (business_date, snapshot_at, store_scope, ad_platform_scope),
  KEY idx_roi_snapshot_date_time (business_date, snapshot_at),
  KEY idx_roi_snapshot_status (ad_data_status, snapshot_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='10-minute cumulative day snapshots for real ROAS';

CREATE TABLE IF NOT EXISTS roi_hourly_delta_facts (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  hour_start_at DATETIME NOT NULL,
  hour_end_at DATETIME NOT NULL,
  business_date DATE NOT NULL,
  timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai',
  store_scope VARCHAR(128) NOT NULL DEFAULT 'newjoy,omurio',
  ad_platform_scope VARCHAR(128) NOT NULL DEFAULT 'meta',
  start_snapshot_id BIGINT DEFAULT NULL,
  end_snapshot_id BIGINT DEFAULT NULL,
  order_count INT NOT NULL DEFAULT 0,
  units INT NOT NULL DEFAULT 0,
  order_revenue_usd DECIMAL(14,2) NOT NULL DEFAULT 0,
  shipping_revenue_usd DECIMAL(14,2) NOT NULL DEFAULT 0,
  ad_spend_usd DECIMAL(14,4) NOT NULL DEFAULT 0,
  true_roas DECIMAL(12,6) DEFAULT NULL,
  order_data_status VARCHAR(32) NOT NULL DEFAULT 'ok',
  ad_data_status VARCHAR(32) NOT NULL DEFAULT 'pending_source',
  last_run_id BIGINT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_roi_hourly_delta (hour_start_at, store_scope, ad_platform_scope),
  KEY idx_roi_hourly_delta_date (business_date, hour_start_at),
  KEY idx_roi_hourly_delta_status (ad_data_status, hour_start_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Hourly deltas derived from cumulative day snapshots';
