CREATE TABLE IF NOT EXISTS mingkong_fine_ai_auto_evaluations (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  material_key CHAR(64) NOT NULL,
  source_bucket VARCHAR(64) NOT NULL DEFAULT '',
  source_rank INT NULL,
  product_code VARCHAR(255) NULL,
  product_url VARCHAR(1000) NULL,
  mk_product_id BIGINT NULL,
  mk_product_link VARCHAR(1000) NULL,
  video_name VARCHAR(500) NULL,
  video_path VARCHAR(1000) NOT NULL,
  video_image_path VARCHAR(1000) NULL,
  cumulative_90_spend DECIMAL(14,2) NOT NULL DEFAULT 0,
  yesterday_spend_delta DECIMAL(14,2) NULL,
  evaluation_run_id VARCHAR(64) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  attempts INT NOT NULL DEFAULT 0,
  last_error VARCHAR(1000) NULL,
  scheduled_run_id BIGINT NULL,
  started_at DATETIME NULL,
  finished_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_mk_fine_ai_auto_material (material_key),
  KEY idx_mk_fine_ai_auto_status (status, updated_at),
  KEY idx_mk_fine_ai_auto_eval_run (evaluation_run_id),
  KEY idx_mk_fine_ai_auto_scheduled_run (scheduled_run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
