-- 数据分析：Meta 广告长期导入批次与周期广告指标

CREATE TABLE IF NOT EXISTS meta_ad_import_batches (
  id                 BIGINT AUTO_INCREMENT PRIMARY KEY,
  source_filename    VARCHAR(255) NOT NULL COMMENT 'Original uploaded Meta report filename',
  file_sha256        CHAR(64)     NOT NULL COMMENT 'Uploaded file content hash',
  import_frequency   VARCHAR(16)  NOT NULL DEFAULT 'custom' COMMENT 'weekly/monthly/custom',
  report_start_date  DATE         DEFAULT NULL,
  report_end_date    DATE         DEFAULT NULL,
  raw_row_count      INT          NOT NULL DEFAULT 0,
  imported_rows      INT          NOT NULL DEFAULT 0,
  updated_rows       INT          NOT NULL DEFAULT 0,
  skipped_rows       INT          NOT NULL DEFAULT 0,
  matched_rows       INT          NOT NULL DEFAULT 0,
  imported_at        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_file_sha256 (file_sha256),
  KEY idx_report_range (report_start_date, report_end_date),
  KEY idx_imported_at (imported_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Meta ad report upload batches';

CREATE TABLE IF NOT EXISTS meta_ad_campaign_metrics (
  id                         BIGINT AUTO_INCREMENT PRIMARY KEY,
  import_batch_id            BIGINT       NOT NULL,
  report_start_date          DATE         NOT NULL,
  report_end_date            DATE         NOT NULL,
  import_frequency           VARCHAR(16)  NOT NULL DEFAULT 'custom',
  campaign_name              VARCHAR(255) NOT NULL,
  normalized_campaign_code   VARCHAR(255) NOT NULL,
  matched_product_code       VARCHAR(128) DEFAULT NULL,
  product_id                 INT          DEFAULT NULL,
  result_count               INT          NOT NULL DEFAULT 0,
  result_metric              VARCHAR(128) DEFAULT NULL,
  spend_usd                  DECIMAL(14,4) NOT NULL DEFAULT 0,
  purchase_value_usd         DECIMAL(14,4) NOT NULL DEFAULT 0,
  roas_purchase              DECIMAL(12,6) DEFAULT NULL,
  cpm_usd                    DECIMAL(12,6) DEFAULT NULL,
  unique_link_click_cost_usd DECIMAL(12,6) DEFAULT NULL,
  link_ctr                   DECIMAL(12,6) DEFAULT NULL,
  campaign_delivery          VARCHAR(32)  DEFAULT NULL,
  link_clicks                INT          NOT NULL DEFAULT 0,
  add_to_cart_count          INT          NOT NULL DEFAULT 0,
  initiate_checkout_count    INT          NOT NULL DEFAULT 0,
  add_to_cart_cost_usd       DECIMAL(12,6) DEFAULT NULL,
  initiate_checkout_cost_usd DECIMAL(12,6) DEFAULT NULL,
  cost_per_result_usd        DECIMAL(12,6) DEFAULT NULL,
  average_purchase_value_usd DECIMAL(12,6) DEFAULT NULL,
  impressions                INT          NOT NULL DEFAULT 0,
  video_avg_play_time        DECIMAL(12,6) DEFAULT NULL,
  raw_json                   JSON         DEFAULT NULL,
  imported_at                DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at                 DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_meta_ad_period_campaign (report_start_date, report_end_date, campaign_name),
  KEY idx_meta_ad_product_period (product_id, report_start_date, report_end_date),
  KEY idx_meta_ad_campaign_code (normalized_campaign_code(191)),
  KEY idx_meta_ad_batch (import_batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Meta ad period-level campaign metrics';
