-- Meta hot posts selection center.
-- Docs-anchor: docs/superpowers/specs/2026-05-13-meta-hot-posts-selection-design.md

CREATE TABLE IF NOT EXISTS meta_hot_post_sync_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  status ENUM('running', 'success', 'failed') NOT NULL DEFAULT 'running',
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at DATETIME NULL,
  duration_seconds INT UNSIGNED NULL,
  request_count INT UNSIGNED NOT NULL DEFAULT 0,
  post_count INT UNSIGNED NOT NULL DEFAULT 0,
  summary_json JSON NULL,
  error_message MEDIUMTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_meta_hot_post_sync_runs_started (started_at),
  KEY idx_meta_hot_post_sync_runs_status_started (status, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS meta_hot_posts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  wedev_post_id BIGINT UNSIGNED NOT NULL,
  page_id VARCHAR(128) NULL,
  post_id VARCHAR(128) NULL,
  bm_page_id VARCHAR(128) NULL,
  post_url VARCHAR(1024) NULL,
  ad_library_url VARCHAR(2048) NULL,
  product_url VARCHAR(2048) NULL,
  product_url_hash CHAR(64) NULL,
  creation_time DATETIME NULL,
  last_synced_at DATETIME NULL,
  likes BIGINT UNSIGNED NULL,
  comments BIGINT UNSIGNED NULL,
  shares BIGINT UNSIGNED NULL,
  latest_likes BIGINT UNSIGNED NULL,
  latest_comments BIGINT UNSIGNED NULL,
  latest_shares BIGINT UNSIGNED NULL,
  sync_period_likes BIGINT UNSIGNED NULL,
  sync_period_hours DECIMAL(12, 4) NULL,
  copycat TINYINT(1) NOT NULL DEFAULT 0,
  select_json JSON NULL,
  video_url VARCHAR(2048) NULL,
  image_url VARCHAR(2048) NULL,
  invisible TINYINT(1) NOT NULL DEFAULT 0,
  invisible_region VARCHAR(32) NULL,
  message_html MEDIUMTEXT NULL,
  raw_json JSON NULL,
  first_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_meta_hot_posts_wedev_post_id (wedev_post_id),
  KEY idx_meta_hot_posts_product_hash (product_url_hash),
  KEY idx_meta_hot_posts_creation (creation_time),
  KEY idx_meta_hot_posts_latest_likes (latest_likes),
  KEY idx_meta_hot_posts_latest_comments (latest_comments)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS meta_hot_post_product_analyses (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  product_url VARCHAR(2048) NOT NULL,
  product_url_hash CHAR(64) NOT NULL,
  status ENUM('pending', 'running', 'done', 'failed') NOT NULL DEFAULT 'pending',
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  last_error MEDIUMTEXT NULL,
  product_title TEXT NULL,
  product_main_image_url VARCHAR(2048) NULL,
  price_min DECIMAL(18, 4) NULL,
  price_max DECIMAL(18, 4) NULL,
  currency VARCHAR(16) NULL,
  sku_prices_json JSON NULL,
  category_l1 VARCHAR(255) NULL,
  category_confidence DECIMAL(8, 6) NULL,
  category_reason TEXT NULL,
  llm_provider VARCHAR(64) NULL,
  llm_model VARCHAR(128) NULL,
  llm_response_json JSON NULL,
  extracted_json JSON NULL,
  analyzed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_meta_hot_post_product_analysis_url_hash (product_url_hash),
  KEY idx_meta_hot_post_product_analyses_status (status, attempts, updated_at),
  KEY idx_meta_hot_post_product_analyses_category (category_l1(120)),
  KEY idx_meta_hot_post_product_analyses_price (price_min)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
