"""LLM UseCase 注册表。"""

from __future__ import annotations

from typing import TypedDict

LLM_PROVIDER_CODES = frozenset({
    "openrouter",
    "doubao",
    "gemini_aistudio",
    "gemini_vertex",
    "gemini_vertex_adc",
})

NON_LLM_PROVIDER_CODES = frozenset({
    "elevenlabs",
    "doubao_asr",
    "local_image",
})

KNOWN_USE_CASE_PROVIDER_CODES = LLM_PROVIDER_CODES | NON_LLM_PROVIDER_CODES


class UseCase(TypedDict):
    code: str
    module: str
    label: str
    description: str
    default_provider: str
    default_model: str
    usage_log_service: str
    units_type: str


def _uc(
    code: str,
    module: str,
    label: str,
    desc: str,
    provider: str,
    model: str,
    service: str,
    units_type: str,
) -> UseCase:
    return {
        "code": code,
        "module": module,
        "label": label,
        "description": desc,
        "default_provider": provider,
        "default_model": model,
        "usage_log_service": service,
        "units_type": units_type,
    }


USE_CASES: dict[str, UseCase] = {
    # 全能视频翻译（多源语种实验模块，独立于 video_translate）
    "omni_translate.lid": _uc(
        "omni_translate.lid",
        "omni_translate",
        "源语言识别（已停用）",
        "历史 LID 用例，当前语音源语言由用户手动选择，不再覆盖 task.source_language",
        "gemini_vertex",
        "gemini-3.1-flash-lite",
        "gemini_vertex",
        "tokens",
    ),
    "omni_av_sync.understand": _uc(
        "omni_av_sync.understand",
        "omni_translate",
        "Omni 音画同步成片理解",
        "Doubao Seed 2.0 Lite 读取合成后成片视频，输出自然语言画面、字幕和明显错位观察笔记",
        "doubao",
        "doubao-seed-2-0-lite-260215",
        "doubao",
        "tokens",
    ),
    "omni_av_sync.assess": _uc(
        "omni_av_sync.assess",
        "omni_translate",
        "Omni 音画同步结构化评估",
        "Gemini 3 Flash 结合 Doubao 视频理解笔记、ASR 和 TTS 文案输出逐段评分卡",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    "omni_av_sync.diagnose": _uc(
        "omni_av_sync.diagnose",
        "omni_translate",
        "Omni 音画同步诊断（旧版）",
        "旧版 Doubao 结构化诊断入口，保留给历史绑定兼容；新流程使用 understand + assess",
        "doubao",
        "doubao-seed-2-0-lite-260215",
        "doubao",
        "tokens",
    ),
    "omni_av_sync.verify": _uc(
        "omni_av_sync.verify",
        "omni_translate",
        "Omni 音画同步复核",
        "Gemini 3 Flash 复核 Doubao 音画同步问题候选，只保留可安全处理的问题",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    # ASR 同语言纯净化（omni 用于 _step_asr_clean，multi 用于 asr_normalize 前置）
    "asr_clean.purify_primary": _uc(
        "asr_clean.purify_primary",
        "asr_clean",
        "ASR 同语言纯净化（主路）",
        "Gemini Flash 主路：把 ASR 结果纯净化为同语言纯净文本，保留时间戳",
        "gemini_vertex",
        "gemini-3.1-flash-lite",
        "gemini_vertex",
        "tokens",
    ),
    "asr_clean.purify_fallback": _uc(
        "asr_clean.purify_fallback",
        "asr_clean",
        "ASR 同语言纯净化（兜底）",
        "Claude Sonnet 兜底：主路校验失败时重跑同样 prompt",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    # 翻译质量评估（subtitle 完成后异步触发，omni / multi 共用）
    "translation_quality.assess": _uc(
        "translation_quality.assess",
        "translation_quality",
        "翻译质量评估",
        "对比原始 ASR / 翻译文案 / 二次 ASR 字幕，给出翻译质量分 + TTS 还原度分",
        "gemini_vertex",
        "gemini-3.1-flash-lite",
        "gemini_vertex",
        "tokens",
    ),
    # AI 视频分析（手动触发，多模态：视频 + 音频 + 文案 + 产品图）
    "video_ai_review.assess": _uc(
        "video_ai_review.assess",
        "video_ai_review",
        "AI 视频分析",
        "多模态评估翻译后的视频：源/目标视频对比、文案/TTS 一致性、产品契合度",
        "gemini_aistudio",
        "gemini-3.5-flash",
        "gemini_aistudio",
        "tokens",
    ),
    # 视频翻译 v1
    "video_translate.localize": _uc(
        "video_translate.localize",
        "video_translate",
        "本土化改写",
        "视频翻译主流程中的本土化文案生成",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    "video_translate.tts_script": _uc(
        "video_translate.tts_script",
        "video_translate",
        "TTS 脚本生成",
        "根据本土化文案切分为适合配音的 TTS 脚本",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    "video_translate.rewrite": _uc(
        "video_translate.rewrite",
        "video_translate",
        "字数收敛重写",
        "TTS 时长不达标时的局部重写",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    "video_translate.tts": _uc(
        "video_translate.tts",
        "video_translate",
        "TTS 配音",
        "ElevenLabs 生成本土化配音",
        "elevenlabs",
        "<runtime>",
        "elevenlabs",
        "chars",
    ),
    "video_translate.tts_language_check": _uc(
        "video_translate.tts_language_check",
        "video_translate",
        "TTS 语言校验",
        "校验最终 TTS 文案是否为目标语言",
        "openrouter",
        "google/gemini-3.1-flash-lite",
        "openrouter",
        "tokens",
    ),
    "voice_selection.assess": _uc(
        "voice_selection.assess",
        "video_translate",
        "TTS 音色大模型排名",
        "Gemini 3.5 Flash 通过 OpenRouter 对当前前十音色做单轮自然度、情绪和表达力排名",
        "openrouter",
        "google/gemini-3.5-flash",
        "openrouter",
        "tokens",
    ),
    "video_translate.asr": _uc(
        "video_translate.asr",
        "video_translate",
        "ASR 识别",
        "豆包 ASR 识别原视频语音",
        "doubao_asr",
        "big-model",
        "doubao_asr",
        "seconds",
    ),
    # 视频翻译 v2
    "video_translate.source_normalize": _uc(
        "video_translate.source_normalize",
        "video_translate",
        "AV source normalize",
        "Clean source ASR text before AV-sync localization without translating or changing timing.",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    "video_translate.shot_notes": _uc(
        "video_translate.shot_notes",
        "video_translate",
        "画面笔记",
        "多模态分析视频并输出逐句画面笔记",
        "openrouter",
        "google/gemini-3.5-flash",
        "openrouter",
        "tokens",
    ),
    "video_translate.av_localize": _uc(
        "video_translate.av_localize",
        "video_translate",
        "音画同步翻译",
        "按画面笔记和时长约束生成本土化口播",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    "video_translate.av_rewrite": _uc(
        "video_translate.av_rewrite",
        "video_translate",
        "音画同步重写",
        "音画同步流程中的局部重写",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    # 日语视频翻译
    "ja_translate.localize": _uc(
        "ja_translate.localize",
        "ja_translate",
        "日语逐句本土化",
        "为日语视频生成自然的日语配音文案",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    "ja_translate.rewrite": _uc(
        "ja_translate.rewrite",
        "ja_translate",
        "日语长度收敛重写",
        "日语视频翻译在 TTS 后按字符预算重写",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    # 翻译实验室
    "translate_lab.shot_translate": _uc(
        "translate_lab.shot_translate",
        "translate_lab",
        "分镜逐句翻译",
        "翻译实验室按分镜逐句翻译口播文案",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    "translate_lab.tts_refine": _uc(
        "translate_lab.tts_refine",
        "translate_lab",
        "TTS 超时压缩改写",
        "翻译实验室在 TTS 超时后压缩改写文案",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    # 文案
    "copywriting.generate": _uc(
        "copywriting.generate",
        "copywriting",
        "文案生成",
        "根据商品信息生成带货文案",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    "copywriting.rewrite": _uc(
        "copywriting.rewrite",
        "copywriting",
        "文案段落重写",
        "单段文案重写",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    "copywriting_translate.generate": _uc(
        "copywriting_translate.generate",
        "copywriting",
        "文案翻译",
        "把英文带货文案翻译成目标语言",
        "openrouter",
        "google/gemini-3.1-flash-lite",
        "openrouter",
        "tokens",
    ),
    # 视频分析
    "video_score.run": _uc(
        "video_score.run",
        "video_analysis",
        "视频评分",
        "按带货维度给视频成片打分",
        "gemini_aistudio",
        "gemini-3.5-flash",
        "gemini_video_analysis",
        "tokens",
    ),
    "video_review.analyze": _uc(
        "video_review.analyze",
        "video_analysis",
        "视频评测",
        "按自定义 prompt 分析视频",
        "gemini_aistudio",
        "gemini-3.5-flash",
        "gemini_video_analysis",
        "tokens",
    ),
    "shot_decompose.run": _uc(
        "shot_decompose.run",
        "video_analysis",
        "分镜拆解",
        "识别镜头切换并生成分镜描述",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    "video_csk.analyze": _uc(
        "video_csk.analyze",
        "video_analysis",
        "CSK 深度分析",
        "对视频做深度特征锁定和关键帧抽取",
        "gemini_aistudio",
        "gemini-3.5-flash",
        "gemini_video_analysis",
        "tokens",
    ),
    # 素材管理
    "material_evaluation.evaluate": _uc(
        "material_evaluation.evaluate",
        "material",
        "素材评估",
        "根据商品图、链接和视频评估市场适配度",
        "openrouter",
        "google/gemini-3.5-flash",
        "openrouter",
        "tokens",
    ),
    "fine_ai_evaluation.product_facts": _uc(
        "fine_ai_evaluation.product_facts",
        "material",
        "精细 AI 评估：产品事实整理",
        "单产品五国精细 AI 评估前置事实整理，输出结构化 JSON",
        "gemini_vertex",
        "gemini-3.5-flash",
        "gemini_vertex",
        "tokens",
    ),
    "fine_ai_evaluation.country": _uc(
        "fine_ai_evaluation.country",
        "material",
        "精细 AI 评估：单国完整评估",
        "单产品单国家完整市场、竞品、价格、素材、落地页和风险评估，输出结构化 JSON",
        "gemini_vertex",
        "gemini-3.5-flash",
        "gemini_vertex",
        "tokens",
    ),
    "xuanpin.today_recommendations": _uc(
        "xuanpin.today_recommendations",
        "material",
        "Xuanpin Today Recommendations",
        "Rank Top500 Dianxiaomi products and Mingkong materials into a daily recommendation shortlist",
        "gemini_vertex",
        "gemini-3.1-flash-lite",
        "gemini_vertex",
        "tokens",
    ),
    "push_quality.check": _uc(
        "push_quality.check",
        "material",
        "推送内容质量检查",
        "推送前检查小语种文案、封面图和视频前 5 秒是否纯净匹配目标语种",
        "openrouter",
        "google/gemini-3.1-flash-lite",
        "openrouter",
        "tokens",
    ),
    # 图片与链接
    "image_translate.detect": _uc(
        "image_translate.detect",
        "image",
        "图片文字检测",
        "判断商品图中是否存在需要翻译的可读文字",
        "gemini_vertex",
        "gemini-3.1-flash-lite",
        "gemini",
        "images",
    ),
    "image_translate.generate": _uc(
        "image_translate.generate",
        "image",
        "图片本地化重绘",
        "用图像模型重绘目标语言商品图",
        "gemini_aistudio",
        "gemini-3.1-flash-image-preview",
        "gemini",
        "images",
    ),
    "image_translate.eval": _uc(
        "image_translate.eval",
        "image",
        "图片翻译效果评估",
        "用 Gemini 3.1 Flash-Lite 评估翻译后的商品图是否纯净、无多语混杂并符合排版要求",
        "openrouter",
        "google/gemini-3.1-flash-lite",
        "openrouter",
        "tokens",
    ),
    "link_check.analyze": _uc(
        "link_check.analyze",
        "image",
        "链接商品图审核",
        "核查外链商品图文字是否匹配目标语言",
        "openrouter",
        "google/gemini-3.1-flash-lite",
        "openrouter",
        "tokens",
    ),
    "link_check.same_image": _uc(
        "link_check.same_image",
        "image",
        "同图判定",
        "比较抓取图与参考图是否属于同一基础图片",
        "openrouter",
        "google/gemini-3.1-flash-lite",
        "openrouter",
        "tokens",
    ),
    # 文本翻译
    "text_translate.generate": _uc(
        "text_translate.generate",
        "text_translate",
        "纯文本翻译",
        "把任意文本翻译到目标语言",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    "title_translate.generate": _uc(
        "title_translate.generate",
        "text_translate",
        "标题翻译",
        "把结构化标题文案翻译成目标语言",
        "openrouter",
        "google/gemini-3.1-flash-lite",
        "openrouter",
        "tokens",
    ),
    "copywriting_translate.audit": _uc(
        "copywriting_translate.audit",
        "text_translate",
        "文案翻译合规审核",
        "用 Gemini Flash-Lite 二次确认已存在文案翻译是否符合 title_translate 规则",
        "openrouter",
        "google/gemini-3.1-flash-lite",
        "openrouter",
        "tokens",
    ),
    # 提示词库
    "prompt_library.generate": _uc(
        "prompt_library.generate",
        "prompt_library",
        "提示词生成",
        "根据需求生成新的系统提示词",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    "prompt_library.translate": _uc(
        "prompt_library.translate",
        "prompt_library",
        "提示词互译",
        "在中英文之间翻译提示词内容",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    # 选品中心
    "meta_hot_posts.categorize": _uc(
        "meta_hot_posts.categorize",
        "xuanpin",
        "Meta 热帖商品类目判断",
        "用 OpenRouter Gemini 3.1 Flash-Lite 根据商品标题判断 TikTok Shop US 一级类目",
        "openrouter",
        "google/gemini-3.1-flash-lite",
        "openrouter",
        "tokens",
    ),
    "meta_hot_posts.translate_message": _uc(
        "meta_hot_posts.translate_message",
        "xuanpin",
        "Meta 热帖文案翻译",
        "把 Meta 热帖视频下方英文文案翻译为简体中文并缓存",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    "meta_hot_posts.translate_product_title": _uc(
        "meta_hot_posts.translate_product_title",
        "xuanpin",
        "Meta 热帖商品标题翻译",
        "把 Meta 热帖商品页英文标题翻译为简体中文并缓存",
        "openrouter",
        "google/gemini-3.1-flash-lite",
        "openrouter",
        "tokens",
    ),
    "meta_hot_posts.europe_fit": _uc(
        "meta_hot_posts.europe_fit",
        "xuanpin",
        "Meta 热帖欧洲投放适配评估",
        "用 OpenRouter google/gemini-3-flash-preview 评估热帖视频和商品链接是否适合直接搬运到欧洲 Meta 广告市场",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    "meta_hot_posts.europe_fit_translate": _uc(
        "meta_hot_posts.europe_fit_translate",
        "xuanpin",
        "Meta 热帖欧洲分析中文解读",
        "使用 OpenRouter google/gemini-3.1-flash-lite 把欧洲适配英文分析翻译为中文解读并缓存",
        "openrouter",
        "google/gemini-3.1-flash-lite",
        "openrouter",
        "tokens",
    ),
    # 视频创作
    "meta_hot_posts.video_copyability": _uc(
        "meta_hot_posts.video_copyability",
        "xuanpin",
        "Meta 热帖视频可抄适配度",
        "使用 OpenRouter google/gemini-3-flash-preview 分析本地化热帖视频是否适合直接抄作业投放美国 Meta 市场广告",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    "meta_hot_posts.video_copyability_translate": _uc(
        "meta_hot_posts.video_copyability_translate",
        "xuanpin",
        "Meta 热帖视频分析中文解读",
        "使用 OpenRouter google/gemini-3.1-flash-lite 把视频可抄英文分析翻译为中文解读并缓存",
        "openrouter",
        "google/gemini-3.1-flash-lite",
        "openrouter",
        "tokens",
    ),
    "video_creation.generate": _uc(
        "video_creation.generate",
        "video_creation",
        "视频创作生成",
        "调用 Seedance 2.0 生成新视频",
        "doubao",
        "doubao-seedance-2-0-260128",
        "doubao",
        "seconds",
    ),
    "video_cover.product_analysis": _uc(
        "video_cover.product_analysis",
        "video_cover",
        "视频封面产品分析",
        "基于商品标题、描述、主图和价格生成封面/文案可用的产品分析报告",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    "video_cover.video_analysis": _uc(
        "video_cover.video_analysis",
        "video_cover",
        "视频封面素材分析",
        "使用 Gemini 3.5 Flash 分析上传视频素材的动作、构图和封面线索",
        "gemini_aistudio",
        "gemini-3.5-flash",
        "gemini_aistudio",
        "tokens",
    ),
    "video_cover.generate": _uc(
        "video_cover.generate",
        "video_cover",
        "视频封面生成",
        "基于商品主图、视频分析、产品分析和文案生成 9:16 竖版短视频封面",
        "local_image",
        "gpt-image-2",
        "local_image",
        "images",
    ),
    "video_cover.ad_copy": _uc(
        "video_cover.ad_copy",
        "video_cover",
        "视频封面文案创作",
        "基于产品分析和视频素材分析生成 5 组欧美 Reels 英文广告文案",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    # 原文标准化（ASR 后插入步骤）
    "asr_normalize.detect_language": _uc(
        "asr_normalize.detect_language",
        "video_translate",
        "原文语言识别",
        "ASR 完成后识别原视频语言以决定标准化路由",
        "openrouter",
        "google/gemini-3.1-flash-lite",
        "openrouter",
        "tokens",
    ),
    "asr_normalize.translate_zh_to_en": _uc(
        "asr_normalize.translate_zh_to_en",
        "video_translate",
        "中文 ASR → en-US 标准化",
        "中文素材 ASR 文本翻译为 en-US（注册保留，runner 当前路由跳过）",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    "asr_normalize.translate_es_to_en": _uc(
        "asr_normalize.translate_es_to_en",
        "video_translate",
        "西语 ASR → en-US 标准化",
        "西班牙语素材 ASR 文本精修翻译为 en-US",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    "asr_normalize.translate_generic_to_en": _uc(
        "asr_normalize.translate_generic_to_en",
        "video_translate",
        "任意源 → en-US 标准化（兜底）",
        "白名单内非中英文素材 ASR 文本通用翻译为 en-US",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    # AI 自动上品
    "ai_listing.copywriting": _uc(
        "ai_listing.copywriting",
        "material",
        "AI 上品详情页生成",
        "根据抓取的竞品描述，利用 Gemini 生成符合高转化经典的英文 HTML 详情页排版",
        "openrouter",
        "google/gemini-3-flash-preview",
        "openrouter",
        "tokens",
    ),
    "ai_listing.transit_parse": _uc(
        "ai_listing.transit_parse",
        "material",
        "AI 二跳落地页解析",
        "结合引流预热页 HTML，智能识别并提取出真正的 Shopify 下单页链接",
        "openrouter",
        "google/gemini-3.1-flash-lite",
        "openrouter",
        "tokens",
    ),
}

def get_use_case(code: str) -> UseCase:
    if code not in USE_CASES:
        raise KeyError(f"unknown use_case: {code}")
    return USE_CASES[code]


def list_by_module() -> dict[str, list[UseCase]]:
    groups: dict[str, list[UseCase]] = {}
    for uc in USE_CASES.values():
        groups.setdefault(uc["module"], []).append(uc)
    return groups


MODULE_LABELS: dict[str, str] = {
    "omni_translate": "全能翻译",
    "video_translate": "视频翻译",
    "ja_translate": "日语翻译",
    "translate_lab": "翻译实验室",
    "copywriting": "文案创作",
    "video_analysis": "视频分析",
    "material": "素材管理",
    "image": "图片 & 链接",
    "text_translate": "文本翻译",
    "prompt_library": "提示词库",
    "video_creation": "视频创作",
    "video_cover": "文案封面生成",
    "asr_clean": "ASR 同语言纯净化",
    "translation_quality": "翻译质量评估",
    "video_ai_review": "AI 视频分析",
    "xuanpin": "选品中心",
}
